development:
  adapter: sqlite3
  database: db/development.sqlite3
  host: localhost
  
  
test: &TEST
  adapter: sqlite3
  database: db/test.sqlite3
  host: localhost
  

production:
  adapter: sqlite3
  database: db/production.sqlite3
  host: localhost
  