development:
  adapter: postgresql
  encoding: utf8
  database: joel_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: joel_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: joel_production
  pool: 5
  username: 
  password:
